// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szdfivpxenexorutudwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6ZGZpdnB4ZW5leG9ydXR1ZHdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzODg1NDMsImV4cCI6MjA1Njk2NDU0M30.mb021u9hZ7lZBI81CycLFWK2WrvpaRjDwK23uKYFBVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);