
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://habndcrbttibaeefjacc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhYm5kY3JidHRpYmFlZWZqYWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTA0MzcsImV4cCI6MjA1NjM2NjQzN30.AFmbgm85ipMJKZvikjYZE537X8AqEzitZju9X41fBU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
